# Generated by Django 6.0.5 on 2026-05-23 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField(default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_visita', models.DateField()),
                ('lugar_interes', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='lugares/')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turismo.lugarturistico')),
            ],
        ),
    ]
